### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by pro4tlzz** [Magisk-Modules-Repo/Sony-Music4Magisk#1]
On the latest APK the name of the app is artist added to %1$s. Here is the link to the image https://twitter.com/Pro4TLZZ/status/995933930586075136?s=19

**Comment by utkarshp64** [comment]
I guess there is a problem with apk. As I don't modify apk. I had reverted module to the previous apk, As there are no major changes in apk. 
Thank you for informing.
